const challenge = {
  truthquestions: [
    "What was the last thing you searched for on your phone?",
    "Who do you think is the worst dressed person in this room?",
    "When was the last time you stole?",
    "Kiss marry kill from this group of friends?",
    "Who is your favorite? Mom or Dad?",
    "If someone offered you $1 million dollars to break up with your girlfriend/boyfriend, would you do it?",
    "If you could go back in time to erase one thing you said or did, what would it be?",
    "If you could suddenly become invisible, what would you do?",
    "Who is one person you pretend to like, but actually don’t?",
    "When was the last time you wet the bed?",
    "Have you ever eaten something off the floor?",
    "Describe your underwear.",
    "What's the sexiest thing about a guy/girl?",
    "If you could go out on a date with a celebrity, who would it be?",
    "Who do you think wears the best looking underwear except you?",
    "If you could eat only one thing for life, what would it be?",
    "If you had to do a gameshow with someone in this room, who would you pick?",
    "Would you go a year without your phone if it meant you could marry the person of your dreams?",
    "Who would you hate to see naked?",
    "How long have you gone without a shower?",
    "If you could only text one person for the rest of your life, but you could never talk to that person face to face, who would that be?",
    "How long have you gone without brushing your teeth?",
    "What's one thing you would never eat on a first date?",
    "What have you seen that you wish you could unsee?",
    "If you could be reincarnated into anyone's body, who would you want to become?",
    "If you switched genders for the day, what would you do?",
    "What's one food that you will never order at a restaurant?",
    "Who would you like to see wear your clothers OPPOSITE GENDER?",
    "If your car broke down in the middle of the road, who in this room would be the last person you would call? Why?",
    "What's the most useless piece of knowledge you know?",
    "Whose fart in this group smells the best by your understanding?",
    "What animal most closely resembles your eating style?",
    "If you could choose to never sweat for the rest of your life or never have to use the bathroom, which would you choose?",
    "If you had to  spend every waking moment with anyone from this group, who would it be?",
    "If you had one day left to live, what would you do first?",
    "Have you ever dated someone while you were still in love with someone else?",
    "Rate everyone in the room from 1 to 10, with 10 being the best personality.",
    "If you could swap one physical feature with everyone in this group what would that be?",
    "Have you ever told a secret you were told to keep?",
    "Associate everyone with an animal HONESTLY NO JOKES?",
    "Who would make the best coouple among the players",
    "Create your dream person by choosing features of people in this group",
    "Have you ever regretted something you did to get a crush's attention?",
    "If you haven't had your first kiss yet, who in this room do you want to have your first kiss with OPPOSITE GENDER?",
    "If you could have been an animal what would have you been?",
    "If you only had 24 hours to live and you could do anything with anyone in this room, who would it be and what would you do with that person?",
    "If you had to give a commencement speech at a college, what would you tell the graduates?",
    "Would you ever get into a long distance relationship?",
    "If you could change one thing on your body, what would it be?",
    "If money didn’t matter, what would your dream job be?",
    "What is the weirdest thing you have ever done in front of a mirror",
    "Have you ever stolen something?",
    "Did you let someone else take the fall for something you did?",
    "What was your childhood nickname?"
  ],
  dares: [
    "Take an embarrassing selfie and post it as your profile picture.",
    "Fill your mouth with water, and each person in the group must tell the funniest joke they know. If you spit up the water, you have to eat a spoonful of dirt.",
    "Until the next round, talk super loud, like nobody can hear you.",
    "Laugh like a mad person",
    "lick the bottom of your shoe PROPERLY .",
    "Let the group pose you in an embarrassing position and take a picture.",
    "Kiss the person to the right on the cheek PROPERLY.",
    "Talk in a strange accent for the rest of the night.",
    "Call the 7th contact in your phone and sing them 30 seconds of a song that the group chooses.",
    "Give A Massage To The person in front of you For 5 Minutes.",
    "Talk without closing your mouth.",
    "Get into a debate with a wall.",
    "Be the pet of person in front of you for the next 3 dares.",
    "SLAP THE ASS OF THE PERSON IN YOUR FEONT HARD",
    "Sit on the lap of the person in front of you for 2 more dares",
    "Sniff the armpits of everyone in the room.",
    "Beg and plead the person to your right not to leave you for that other boy or girl. Weeping, gnashing of teeth, and wailing is encouraged.PROPERLY",
    "Seduce a member of the same gender in the group.",
    " Go to the bathroom, take off your underwear and put it on your head.Show that you did it to a person of the same gender",
    "Close your eyes and send a blind text to a random person",
    "Propose to the one on your right and left, PROPERLY",
    "Let the person in front of you and someone of his choice do your hair",
    "Go to the next room and ask your neighbor for bananas",
    "Lick someone’s foot 2 times.",
    "Gaze into the eyes of the person to the left for 30 seconds.",
    "Slow dance to a fast song.",
    "Hop like a kangaroo for a minute and cover the entire room.",
    "Tie your hand to the person on your right for 5 dares",
    "Do asmr for the person in the front NO LAUGHING.",
    "Let the person in front of you pull off a hair from your body",
    "Go back and forth under the table until it’s your turn again.",
    "Call 5 different people and talk to them in 5 different accents.",
    "Act like the person in front of you is your BF/GF properly",
    "Give a piggyback ride to the person front of you around the room"
  ],
  penalty: [
    "Get beaten up by the whole group HARD and the one who dosent beat also gets beaten up",
   
  ]
};
